hyper:
    batch_size: 8
    gpu_ids: 0
    logs_dir: /home/weiy1/code/commonscenes/experiments/diff_crossattn_final
    results_dir: /home/weiy1/code/commonscenes/experiments/diff_crossattn_final
    # logs_dir: /home/weiy1/code/commonscenes/experiments/g2sv1/diff_crossattn
    # results_dir: /home/weiy1/code/commonscenes/experiments/g2sv1/diff_crossattn
    name: ./
    isTrain: True
    device: 'cuda'
    distributed: 0
dataset:
    res: 64
    trunc_thres: 0.2
    ratio: 1
network:
    model: sdfusion-difflayo
    ckpt: null
    df_cfg: /home/weiy1/code/commonscenes/config/sdfusion-difflayo.yaml
    ddim_steps: 100
    ddim_eta: 0.0
    uc_scale: 3.0
    vq_model: vqvae
    vq_cfg: /home/weiy1/code/commonscenes/config/vqvae_snet.yaml
    vq_dset: None
    vq_cat: None
    vq_ckpt: /home/weiy1/code/commonscenes/scripts/checkpoint/vqvae_threedfront_best.pth
misc:
    debug: 0
    seed: 111
    backend: gloo
    local_rank: 0

training:
    lr: 1e-5
    lr_policy: lambda
    lr_decay_iters: 50
    lambda_L1: 10.0
